# Generated by Django 3.2.23 on 2023-12-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeonDemonSocialApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
