# Generated by Django 3.2.23 on 2023-12-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeonDemonSocialApp', '0002_remove_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='likes',
        ),
    ]
