# Generated by Django 3.2.23 on 2023-12-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeonDemonSocialApp', '0003_remove_uploadimage_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='alt',
            field=models.CharField(default='placeholder', max_length=50),
        ),
    ]
