# Generated by Django 3.2.23 on 2023-12-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeonDemonSocialApp', '0004_uploadimage_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='alt',
            field=models.TextField(max_length=50),
        ),
    ]
