# Generated by Django 3.2.23 on 2023-12-21 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NeonDemonSocialApp', '0006_auto_20231221_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
