# Generated by Django 3.2.24 on 2024-02-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeonDemonSocialApp', '0008_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
